import { PrettierOptionType } from "@/interface/PrettierOptionType";

const options: PrettierOptionType[] = [
	{
		name: "Experimental Ternaries",
		since: "",
		key: "experimentalTernaries",
		description: "Use new ternary formatting (future default).",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "true — aligns with future Prettier default behavior",
	},
	{
		name: "Experimental Operator Position",
		since: "",
		key: "experimentalOperatorPosition",
		description: "Control where line-break operators appear.",
		type: "buttons",
		options: ["start", "end"],
		validate: "string",
		recommend: `"end" — more common and readable style`,
	},
	{
		name: "Print Width",
		since: "",
		key: "printWidth",
		description: "Max line length before wrapping.",
		type: "input",
		validate: "integer",
		recommend: "80 — widely accepted line length limit for readability",
	},
	{
		name: "Tab Width",
		since: "",
		key: "tabWidth",
		description: "Spaces per indentation level.",
		type: "input",
		validate: "integer",
		recommend: "2 — compact and commonly used in modern JS",
	},
	{
		name: "Tabs",
		since: "",
		key: "useTabs",
		description: "Use tabs instead of spaces.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "false — spaces are more consistent across environments",
	},
	{
		name: "Semicolons",
		since: "",
		key: "semi",
		description: "Add semicolons at line ends.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "true — prevents ASI bugs and aligns with default",
	},
	{
		name: "Quotes",
		since: "",
		key: "singleQuote",
		description: "Prefer single over double quotes.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "true — fewer escape characters in JS",
	},
	{
		name: "Quote Props",
		since: "",
		key: "quoteProps",
		description: "When to quote object properties.",
		type: "buttons",
		options: ["as-needed", "consistent", "preserve"],
		validate: "string",
		recommend: `"as-needed" — keeps output clean and minimal`,
	},
	{
		name: "JSX Quotes",
		since: "",
		key: "jsxSingleQuote",
		description: "Use single quotes in JSX.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "false — HTML convention uses double quotes",
	},
	{
		name: "Trailing Commas",
		since: "",
		key: "trailingComma",
		description: "Add trailing commas in multiline.",
		type: "buttons",
		options: ["none", "es5", "all"],
		validate: "string",
		recommend: `"es5" — adds commas where valid in ES5 (more maintainable)`,
	},
	{
		name: "Bracket Spacing",
		since: "",
		key: "bracketSpacing",
		description: "Add spaces inside object braces.",
		type: "buttons",
		options: [true, false],
		examples: ["{ foo: bar }", "{foo: bar}"],
		validate: "boolean",
		recommend: "true — improves readability",
	},
	{
		name: "Object Wrap",
		since: "3.5.0",
		key: "objectWrap",
		description: "How to wrap object literals.",
		type: "buttons",
		options: ["preserve", "collapse"],
		validate: "string",
		recommend: `"preserve" — respects original formatting`,
	},
	{
		name: "Bracket Line",
		since: "",
		key: "bracketSameLine",
		description: "Place closing bracket on same line.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "false — improves readability and consistency",
	},
	{
		name: "Arrow Function Parentheses",
		since: "1.9.0",
		key: "arrowParens",
		description: "Use parentheses around arrow params.",
		type: "buttons",
		options: ["avoid", "always"],
		examples: ["x => x", "(x) => x"],
		validate: "string",
		recommend: `"always" — reduces ambiguity in complex cases`,
	},
	{
		name: "Range Start",
		since: "",
		key: "rangeStart",
		description: "Start formatting from character index.",
		type: "input",
		validate: "integer",
		recommend: "0 — usually start from beginning",
	},
	{
		name: "Range End",
		since: "",
		key: "rangeEnd",
		description: "End formatting at character index.",
		type: "input",
		validate: "integer",
		recommend: "Infinity — typically format the whole file",
	},
	{
		name: "Parser",
		since: "",
		key: "parser",
		description: "Force specific parser to use.",
		type: "select",
		options: [
			"babel",
			"babel-flow",
			"babel-ts",
			"flow",
			"typescript",
			"espree",
			"meriyah",
			"acorn",
			"css",
			"scss",
			"less",
			"json",
			"json5",
			"jsonc",
			"json-stringify",
			"graphql",
			"markdown",
			"mdx",
			"html",
			"vue",
			"angular",
			"lwc",
			"yaml",
		],
		validate: "string",
		recommend: `"typescript" or "babel" — depending on your project type`,
	},
	{
		name: "File Path",
		since: "",
		key: "filePath",
		description: "Used to infer the parser.",
		type: "input",
		validate: "string",
		recommend: "Provide relevant file path like 'src/index.tsx'",
	},
	{
		name: "Require Pragma",
		since: "1.7.0",
		key: "requirePragma",
		description: "Only format files with @format comment.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "false — not needed unless working in large monorepos",
	},
	{
		name: "Insert Pragma",
		since: "1.8.0",
		key: "insertPragma",
		description: "Add @format comment to output.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "false — useful if using 'requirePragma', else unnecessary",
	},
	{
		name: "Prose Wrap",
		since: "1.8.2",
		key: "proseWrap",
		description: "Wrap markdown text.",
		type: "buttons",
		options: ["always", "never", "preserve"],
		validate: "string",
		recommend: `"preserve" — maintains author’s formatting intent`,
	},
	{
		name: "HTML Whitespace Sensitivity",
		since: "1.15.0",
		key: "htmlWhitespaceSensitivity",
		description: "Control whitespace in HTML.",
		type: "buttons",
		options: ["css", "strict", "ignore"],
		validate: "string",
		recommend: `"css" — respects browser rendering behavior`,
	},
	{
		name: "Vue Indent Script and Style",
		since: "1.19.0",
		key: "vueIndentScriptAndStyle",
		description: "Indent `<script>` and `<style>` in Vue.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "true — improves structure and readability",
	},
	{
		name: "End of Line",
		since: "1.15.0",
		key: "endOfLine",
		description: "Set line ending character.",
		type: "buttons",
		options: ["lf", "crlf", "cr", "auto"],
		validate: "string",
		recommend: `"lf" — most consistent across environments`,
	},
	{
		name: "Embedded Language Formatting",
		since: "2.1.0",
		key: "embeddedLanguageFormatting",
		description: "Format code in template literals.",
		type: "buttons",
		options: ["auto", "off"],
		validate: "string",
		recommend: `"auto" — allows Prettier to decide what's safe`,
	},
	{
		name: "Single Attribute Per Line",
		since: "2.6.0",
		key: "singleAttributePerLine",
		description: "Force single-line attributes in JSX/HTML.",
		type: "buttons",
		options: [true, false],
		validate: "boolean",
		recommend: "false — multiple attributes per line is more compact",
	},
	{
		name: "Official Plugins",
		since: "",
		key: "plugins",
		description: "Use official Prettier plugins.",
		type: "multiselect",
		options: [
			"@prettier/plugin-php",
			"@prettier/plugin-pug",
			"@prettier/plugin-ruby",
			"@prettier/plugin-xml",
			"prettier-plugin-tailwindcss",
		],
		validate: "string[]",
		recommend: "Select only those required for your codebase",
	},
];

export default options;
