import {
	PrettierOptionTypeEnum,
	PrettierOptionValidateEnum,
} from "@/enum/prettierOption";
import { PrettierOptionType } from "@/interface/PrettierOptionType";

const options: PrettierOptionType[] = [
	{
		name: "Experimental Ternaries",
		since: "",
		key: "experimentalTernaries",
		description: "Use new ternary formatting (future default).",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Experimental Operator Position",
		since: "",
		key: "experimentalOperatorPosition",
		description: "Control where line-break operators appear.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["start", "end"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Print Width",
		since: "",
		key: "printWidth",
		description: "Max line length before wrapping.",
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: "Tab Width",
		since: "",
		key: "tabWidth",
		description: "Spaces per indentation level.",
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: "Tabs",
		since: "",
		key: "useTabs",
		description: "Use tabs instead of spaces.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Semicolons",
		since: "",
		key: "semi",
		description: "Add semicolons at line ends.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Quotes",
		since: "",
		key: "singleQuote",
		description: "Prefer single over double quotes.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Quote Props",
		since: "",
		key: "quoteProps",
		description: "When to quote object properties.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["as-needed", "consistent", "preserve"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "JSX Quotes",
		since: "",
		key: "jsxSingleQuote",
		description: "Use single quotes in JSX.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Trailing Commas",
		since: "",
		key: "trailingComma",
		description: "Add trailing commas in multiline.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["none", "es5", "all"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Bracket Spacing",
		since: "",
		key: "bracketSpacing",
		description: "Add spaces inside object braces.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Object Wrap",
		since: "3.5.0",
		key: "objectWrap",
		description: "How to wrap object literals.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["preserve", "collapse"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Bracket Line",
		since: "",
		key: "bracketSameLine",
		description: "Place closing bracket on same line.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Arrow Function Parentheses",
		since: "1.9.0",
		key: "arrowParens",
		description: "Use parentheses around arrow params.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["avoid", "always"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Range Start",
		since: "",
		key: "rangeStart",
		description: "Start formatting from character index.",
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: "Range End",
		since: "",
		key: "rangeEnd",
		description: "End formatting at character index.",
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.INTEGER,
	},
	{
		name: "Parser",
		since: "",
		key: "parser",
		description: "Force specific parser to use.",
		type: PrettierOptionTypeEnum.SELECT,
		options: [
			"babel",
			"babel-flow",
			"babel-ts",
			"flow",
			"typescript",
			"espree",
			"meriyah",
			"acorn",
			"css",
			"scss",
			"less",
			"json",
			"json5",
			"jsonc",
			"json-stringify",
			"graphql",
			"markdown",
			"mdx",
			"html",
			"vue",
			"angular",
			"lwc",
			"yaml",
		],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "File Path",
		since: "",
		key: "filePath",
		description: "Used to infer the parser.",
		type: PrettierOptionTypeEnum.INPUT,
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Require Pragma",
		since: "1.7.0",
		key: "requirePragma",
		description: "Only format files with @format comment.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Insert Pragma",
		since: "1.8.0",
		key: "insertPragma",
		description: "Add @format comment to output.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Prose Wrap",
		since: "1.8.2",
		key: "proseWrap",
		description: "Wrap markdown text.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["always", "never", "preserve"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "HTML Whitespace Sensitivity",
		since: "1.15.0",
		key: "htmlWhitespaceSensitivity",
		description: "Control whitespace in HTML.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["css", "strict", "ignore"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Vue Indent Script and Style",
		since: "1.19.0",
		key: "vueIndentScriptAndStyle",
		description: "Indent `<script>` and `<style>` in Vue.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "End of Line",
		since: "1.15.0",
		key: "endOfLine",
		description: "Set line ending character.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["lf", "crlf", "cr", "auto"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Embedded Language Formatting",
		since: "2.1.0",
		key: "embeddedLanguageFormatting",
		description: "Format code in template literals.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: ["auto", "off"],
		validate: PrettierOptionValidateEnum.STRING,
	},
	{
		name: "Single Attribute Per Line",
		since: "2.6.0",
		key: "singleAttributePerLine",
		description: "Force single-line attributes in JSX/HTML.",
		type: PrettierOptionTypeEnum.BUTTONS,
		options: [true, false],
		validate: PrettierOptionValidateEnum.BOOLEAN,
	},
	{
		name: "Official Plugins",
		since: "",
		key: "plugins",
		description: "Use official Prettier plugins.",
		type: PrettierOptionTypeEnum.MULTISELECT,
		options: [
			"@prettier/plugin-php",
			"@prettier/plugin-pug",
			"@prettier/plugin-ruby",
			"@prettier/plugin-xml",
			"prettier-plugin-tailwindcss",
		],
		validate: PrettierOptionValidateEnum.STRING_ARRAY,
	},
];

export default options;
